name: HostingerDeploy

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: setup environment variables
        run: |
          cp .env.example .env
      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install node dependencies
        run: npm ci
      - name: build npm and generate key
        run: |
          php artisan key:generate
          npm run build
      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy php to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd domains/chatter.website
            php artisan down
            git pull
            composer i --no-interaction -q --no-progress
            php artisan migrate --force
            php artisan optimize
            php artisan up
          name: Copy Build Files To Target Server
          run: |
            rsync -r -e "ssh ${{ secrets.SSH_PORT }}" ${{ github.workspace }}/public/build/ ${{ secrets.SSH_USERNAME }}@{{secrets.SSH_HOST}}:~/domains/chatter.website/public/build
