name: HostingerDeploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup environment variables
        run: |
          cp .env.example .env
          echo "BROADCAST_DRIVER=log" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "CACHE_DRIVER=file" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "LOG_CHANNEL=stack" >> .env

      - name: Install composer Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install node dependencies
        run: npm ci

      - name: Build npm and generate key
        run: |
          php artisan key:generate --ansi
          npm run build

      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: public/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: public/build

      - name: Deploy PHP to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd domains/chatter.website
            php artisan down
            git pull
            ~/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            php artisan migrate --force
            php artisan optimize
            php artisan up

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Build Files To Target Server
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
            public/build/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/domains/chatter.website/public/build
